version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      all-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      all-deps:
        patterns:
          - "*"
